# version: '3.8'

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: hesabyar-mysql
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: hesabyar_db
#       MYSQL_USER: hesabyar_user
#       MYSQL_PASSWORD: hesabyar_pass
#     ports:
#       - '3306:3306'
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - hesabyar-network

#   backend:
#     build: .
#     container_name: hesabyar-backend
#     restart: unless-stopped
#     ports:
#       - '3000:3000'
#     environment:
#       - DB_HOST=mysql
#       - DB_PORT=3306
#       - DB_USERNAME=hesabyar_user
#       - DB_PASSWORD=hesabyar_pass
#       - DB_NAME=hesabyar_db
#       - UPLOAD_FOLDER=uploads
#       - STATIC_URL=http://localhost:3000/uploads
#     depends_on:
#       - mysql
#     volumes:
#       - .:/app
#       - /app/node_modules
#       - ./uploads:/app/uploads
#     networks:
#       - hesabyar-network

# volumes:
#   mysql_data:

# networks:
#   hesabyar-network:
version: '3.9'

services:
  asansorland_backend:
    image: asansorland_backend:1.0
    container_name: asansorland_backend
    restart: unless-stopped
    ports:
      - '3001:3001'

    environment:
      HESABYAR_NODE_ENV: developement
      UPLOAD_FOLDER: uploads
      CONFIG_SECRET_KEY: superSecretKeyFor@ConfigEncryption!
      JWT_SECRET: jwtSuperSecret@14040429!
      JWT_EXPIRES_IN: 1d
      USER_LINK_SECRET: userjwtSuperSecret@14040429!
      USER_LINK_EXPIRES_IN: 2h

      PROFORMA_LINK_SECRET: proformajwtSuperSecret@14040429!
      PROFORMA_LINK_EXPIRES_IN: 2h

      INVOICE_LINK_SECRET: invoicejwtSuperSecret@14040429!
      INVOICE_LINK_EXPIRES_IN: 2h

      DEPOT_LINK_SECRET: depotjwtSuperSecret@14040429!
      DEPOT_LINK_EXPIRES_IN: 2h

      DB_HOST: asansorland_mysql_db
      DB_PORT: 3306
      DB_USERNAME: asansorland
      DB_PASSWORD: fmFHGJSFNyNBBx7D/cS7XOk9aFJKURZTbvEdb77Aq8J7s12AMZO0m48V5vv+8Bg=
      DB_NAME: asansorland_db

      SEPDB_HOST: 79.127.37.194
      SEPDB_PORT: 1433
      SEPDB_DBNAME: Sepidar01
      SEPDB_USERNAME: sa
      SEPDB_PASSWORD: 7kTOqY3qd6haNcONaiMPEHvkAKC8HXoUE1Z5t7G54sord+I7xuGv1yxb62oh

    networks:
      - asansorland-network

networks:
  asansorland-network:
    external: true
