import { Proforma } from '../proforma/proforma.entity';
import { User } from 'src/users/users.entity';
import { Customer } from 'src/customer/customer.entity';
import { PaymentTypes } from 'src/common/decorators/payment.enum';
import { InvoiceGoods } from './invoice-good.entity';
export declare class Invoice {
    id: number;
    title: string;
    isSent: boolean;
    isAccepted: boolean;
    acceptedBy: User;
    updateAt: Date;
    sepidarId: string;
    proforma: Proforma;
    customer: Customer;
    totalAmount: number;
    paymentStatus: PaymentTypes;
    chequeDate: Date;
    chequeAmount: number;
    chequeSerial: number;
    paperMoneyDate: Date;
    paperMoneyAmount: number;
    paperMoneySerial: number;
    trustIssueDate: Date;
    approvedFile: string;
    customerLink: string;
    invoiceGoods: InvoiceGoods[];
    createdAt: Date;
    createdBy: User;
}
