export enum Banks {
  Meli = 'ملی',
  Melat = 'ملت',
  Saderat = 'صادرات',
  Keshavarzi = 'کشاورزی',
  Sepah = 'سپه',
  MehreIran = 'مهر ایران',
  Mehr = 'مهر',
  Ayande = 'آینده',
  Dey = 'دی',
  Tourism = 'گردشگری',
  Refah = 'رفاه',
  Tejarat = 'تجارت',
  ToseTavon = 'توسعه تعاون',
  ToseSaderat = 'توسعه صادارت',
  Saman = 'سامان',
  Pasargad = 'پاسارگاد',
  Parsian = 'پارسیان',
  Maskan = 'مسکن',
  Karafarin = 'کارآفرین',
}
